# Build the WASM module and create a distributable zip package on Windows.
#
# Stage 1 - Build: compiles the Rust crate to WASM via wasm-pack.
# Stage 2 - Package: copies viewer + WASM binaries into a dated zip that
#            anyone can download and serve to run in any modern browser on
#            Windows, macOS, or Linux.
#
# Usage: .\package.ps1  [-SkipBuild]
#
# Prerequisites (one-time setup):
#   rustup target add wasm32-unknown-unknown
#   cargo install wasm-pack
param([switch]$SkipBuild)

$ErrorActionPreference = "Stop"
Push-Location $PSScriptRoot

try {
    # ── Stage 1: Build ──────────────────────────────────────────────────────
    if (-not $SkipBuild) {
        Write-Host "==> Stage 1: Building WASM module"
        & "$PSScriptRoot\build.ps1"
    }

    # ── Stage 2: Package ────────────────────────────────────────────────────
    $version     = Get-Date -Format "yyyyMMdd"
    $packageName = "wasm-agent-viewer-$version"
    Write-Host "==> Stage 2: Packaging $packageName.zip"

    if (Test-Path $packageName) { Remove-Item -Recurse -Force $packageName }
    New-Item -ItemType Directory -Path "$packageName\pkg" | Out-Null

    # Viewer HTML
    Copy-Item "viewer\index.html" "$packageName\"

    # WASM binaries and JS glue (generated by wasm-pack)
    Copy-Item "viewer\pkg\wasm_agent.js"           "$packageName\pkg\"
    Copy-Item "viewer\pkg\wasm_agent_bg.wasm"      "$packageName\pkg\"
    Copy-Item "viewer\pkg\wasm_agent.d.ts"         "$packageName\pkg\"
    Copy-Item "viewer\pkg\wasm_agent_bg.wasm.d.ts" "$packageName\pkg\"
    Copy-Item "viewer\pkg\package.json"            "$packageName\pkg\"

    $requiredFiles = @(
        "$packageName\index.html",
        "$packageName\pkg\wasm_agent.js",
        "$packageName\pkg\wasm_agent_bg.wasm",
        "$packageName\pkg\wasm_agent.d.ts",
        "$packageName\pkg\wasm_agent_bg.wasm.d.ts",
        "$packageName\pkg\package.json"
    )

    foreach ($f in $requiredFiles) {
        if (-not (Test-Path $f)) {
            throw "Missing required package file: $f"
        }
    }

    # ── start-server.sh (Linux / macOS) ────────────────────────────────────
    @'
#!/usr/bin/env bash
# Serve the WASM viewer over HTTP.
# WASM ES-module imports require HTTP — opening index.html directly won't work.
#
# Usage:
#   ./start-server.sh              # localhost only, port 8000
#   ./start-server.sh 8080         # custom port, localhost only
#   ./start-server.sh 8000 0.0.0.0 # LAN access (all interfaces) for Android/iOS testing
PORT="${1:-8000}"
BIND="${2:-127.0.0.1}"
cd "$(dirname "$0")"

LAN_IP=""
if [ "$BIND" = "0.0.0.0" ]; then
    LAN_IP="$(python3 -c "import socket; s=socket.socket(); s.connect(('8.8.8.8',80)); print(s.getsockname()[0]); s.close()" 2>/dev/null || \
              hostname -I 2>/dev/null | awk '{print $1}' || echo "")"
fi

echo "Starting server at http://${BIND}:${PORT}"
if [ -n "$LAN_IP" ]; then
    echo "LAN access (Android/iOS): http://${LAN_IP}:${PORT}"
fi
echo "Open the URL in any modern browser (Chrome, Firefox, Safari, Edge)."
echo "Press Ctrl+C to stop."

SERVE_SCRIPT='
import sys, os
sys.path.insert(0, os.getcwd())
from http.server import HTTPServer, SimpleHTTPRequestHandler

class WasmHandler(SimpleHTTPRequestHandler):
    extensions_map = {
        **SimpleHTTPRequestHandler.extensions_map,
        ".wasm": "application/wasm",
    }
    def log_message(self, fmt, *args):
        pass

port = int(sys.argv[1]) if len(sys.argv) > 1 else 8000
bind = sys.argv[2] if len(sys.argv) > 2 else "127.0.0.1"
httpd = HTTPServer((bind, port), WasmHandler)
httpd.serve_forever()
'

if command -v python3 &>/dev/null; then
    python3 -c "$SERVE_SCRIPT" "${PORT}" "${BIND}"
elif command -v python &>/dev/null; then
    python -c "$SERVE_SCRIPT" "${PORT}" "${BIND}"
else
    echo "Python not found. Serve this directory with any HTTP server, e.g.:"
    echo "  npx serve ."
    echo "  php -S ${BIND}:${PORT}"
    exit 1
fi
'@ | Set-Content -Path "$packageName\start-server.sh" -Encoding UTF8

    # ── start-server.bat (Windows cmd) ─────────────────────────────────────
    @'
@echo off
set PORT=8000
set BIND=127.0.0.1
if not "%~1"=="" set PORT=%~1
if not "%~2"=="" set BIND=%~2
echo Starting server at http://%BIND%:%PORT%
if "%BIND%"=="0.0.0.0" echo For Android/iOS testing, use your machine's LAN IP on port %PORT%
echo Open that URL in any modern browser (Chrome, Firefox, Safari, Edge).
echo Press Ctrl+C to stop.
cd /d "%~dp0"
python -c "from http.server import HTTPServer,SimpleHTTPRequestHandler; m={**SimpleHTTPRequestHandler.extensions_map,'.wasm':'application/wasm'}; SimpleHTTPRequestHandler.extensions_map=m; HTTPServer(('%BIND%',%PORT%),SimpleHTTPRequestHandler).serve_forever()"
if errorlevel 1 (
    echo Python not found. Serve this directory with any HTTP server, e.g.:
    echo   npx serve .
    pause
)
'@ | Set-Content -Path "$packageName\start-server.bat" -Encoding UTF8

    # ── start-server.ps1 (Windows PowerShell) ──────────────────────────────
    @'
param(
    [int]$Port = 8000,
    [string]$Bind = "127.0.0.1"
)
Set-Location $PSScriptRoot
Write-Host "Starting server at http://${Bind}:${Port}"
if ($Bind -eq "0.0.0.0") {
    $lanIP = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.PrefixOrigin -eq "Dhcp" -or $_.PrefixOrigin -eq "Manual" } | Select-Object -First 1).IPAddress
    if ($lanIP) { Write-Host "LAN access (Android/iOS): http://${lanIP}:${Port}" }
}
Write-Host "Open that URL in any modern browser (Chrome, Firefox, Safari, Edge)."
Write-Host "Press Ctrl+C to stop."
$serveScript = @'
from http.server import HTTPServer, SimpleHTTPRequestHandler
import sys
class WasmHandler(SimpleHTTPRequestHandler):
    extensions_map = {**SimpleHTTPRequestHandler.extensions_map, ".wasm": "application/wasm"}
    def log_message(self, fmt, *args): pass
HTTPServer((sys.argv[1], int(sys.argv[2])), WasmHandler).serve_forever()
'@
if (Get-Command python3 -ErrorAction SilentlyContinue) {
    python3 -c $serveScript $Bind $Port
} elseif (Get-Command python -ErrorAction SilentlyContinue) {
    python -c $serveScript $Bind $Port
} else {
    Write-Host "Python not found. Serve this directory with any HTTP server, e.g.:"
    Write-Host "  npx serve ."
}
'@ | Set-Content -Path "$packageName\start-server.ps1" -Encoding UTF8

    # ── Create zip ──────────────────────────────────────────────────────────
    $zipPath = "$PSScriptRoot\$packageName.zip"
    Compress-Archive -Path $packageName -DestinationPath $zipPath -Force
    Remove-Item -Recurse -Force $packageName

    Write-Host ""
    Write-Host "Done. Created $packageName.zip"
    Write-Host "Distribute the archive."
    Write-Host "Recipients: extract it, then run start-server.bat or start-server.ps1"
    Write-Host "and open http://localhost:8000 in any modern browser."

} finally {
    Pop-Location
}
