# Build the WASM module and create a distributable zip package on Windows.
#
# Stage 1 - Build: compiles the Rust crate to WASM via wasm-pack.
# Stage 2 - Package: copies viewer + WASM binaries into a dated zip that
#            anyone can download and serve to run in any modern browser on
#            Windows, macOS, or Linux.
#
# Usage: .\package.ps1  [-SkipBuild]
#
# Prerequisites (one-time setup):
#   rustup target add wasm32-unknown-unknown
#   cargo install wasm-pack
param([switch]$SkipBuild)

$ErrorActionPreference = "Stop"
Push-Location $PSScriptRoot

try {
    # ── Stage 1: Build ──────────────────────────────────────────────────────
    if (-not $SkipBuild) {
        Write-Host "==> Stage 1: Building WASM module"
        & "$PSScriptRoot\build.ps1"
    }

    # ── Stage 2: Package ────────────────────────────────────────────────────
    $version     = Get-Date -Format "yyyyMMdd"
    $packageName = "wasm-agent-viewer-$version"
    Write-Host "==> Stage 2: Packaging $packageName.zip"

    if (Test-Path $packageName) { Remove-Item -Recurse -Force $packageName }
    New-Item -ItemType Directory -Path "$packageName\pkg" | Out-Null

    # Viewer HTML
    Copy-Item "viewer\index.html" "$packageName\"

    # WASM binaries and JS glue (generated by wasm-pack)
    Copy-Item "viewer\pkg\wasm_agent.js"           "$packageName\pkg\"
    Copy-Item "viewer\pkg\wasm_agent_bg.wasm"      "$packageName\pkg\"
    Copy-Item "viewer\pkg\wasm_agent.d.ts"         "$packageName\pkg\"
    Copy-Item "viewer\pkg\wasm_agent_bg.wasm.d.ts" "$packageName\pkg\"
    Copy-Item "viewer\pkg\package.json"            "$packageName\pkg\"

    $requiredFiles = @(
        "$packageName\index.html",
        "$packageName\pkg\wasm_agent.js",
        "$packageName\pkg\wasm_agent_bg.wasm",
        "$packageName\pkg\wasm_agent.d.ts",
        "$packageName\pkg\wasm_agent_bg.wasm.d.ts",
        "$packageName\pkg\package.json"
    )

    foreach ($f in $requiredFiles) {
        if (-not (Test-Path $f)) {
            throw "Missing required package file: $f"
        }
    }

    # ── start-server.sh (Linux / macOS) ────────────────────────────────────
    @'
#!/usr/bin/env bash
# Serve the WASM viewer over HTTP.
# WASM ES-module imports require HTTP — opening index.html directly won't work.
PORT="${1:-8000}"
echo "Starting server at http://localhost:${PORT}"
echo "Open that URL in any modern browser (Chrome, Firefox, Safari, Edge)."
echo "Press Ctrl+C to stop."
cd "$(dirname "$0")"
if command -v python3 &>/dev/null; then
    python3 -m http.server "${PORT}"
elif command -v python &>/dev/null; then
    python -m http.server "${PORT}"
else
    echo "Python not found. Serve this directory with any HTTP server, e.g.:"
    echo "  npx serve ."
    echo "  php -S localhost:${PORT}"
    exit 1
fi
'@ | Set-Content -Path "$packageName\start-server.sh" -Encoding UTF8

    # ── start-server.bat (Windows cmd) ─────────────────────────────────────
    @'
@echo off
set PORT=8000
if not "%~1"=="" set PORT=%~1
echo Starting server at http://localhost:%PORT%
echo Open that URL in any modern browser (Chrome, Firefox, Safari, Edge).
echo Press Ctrl+C to stop.
cd /d "%~dp0"
python -m http.server %PORT%
if errorlevel 1 (
    echo Python not found. Serve this directory with any HTTP server, e.g.:
    echo   npx serve .
    pause
)
'@ | Set-Content -Path "$packageName\start-server.bat" -Encoding UTF8

    # ── start-server.ps1 (Windows PowerShell) ──────────────────────────────
    @'
param([int]$Port = 8000)
Set-Location $PSScriptRoot
Write-Host "Starting server at http://localhost:$Port"
Write-Host "Open that URL in any modern browser (Chrome, Firefox, Safari, Edge)."
Write-Host "Press Ctrl+C to stop."
if (Get-Command python3 -ErrorAction SilentlyContinue) {
    python3 -m http.server $Port
} elseif (Get-Command python -ErrorAction SilentlyContinue) {
    python -m http.server $Port
} else {
    Write-Host "Python not found. Serve this directory with any HTTP server, e.g.:"
    Write-Host "  npx serve ."
}
'@ | Set-Content -Path "$packageName\start-server.ps1" -Encoding UTF8

    # ── Create zip ──────────────────────────────────────────────────────────
    $zipPath = "$PSScriptRoot\$packageName.zip"
    Compress-Archive -Path $packageName -DestinationPath $zipPath -Force
    Remove-Item -Recurse -Force $packageName

    Write-Host ""
    Write-Host "Done. Created $packageName.zip"
    Write-Host "Distribute the archive."
    Write-Host "Recipients: extract it, then run start-server.bat or start-server.ps1"
    Write-Host "and open http://localhost:8000 in any modern browser."

} finally {
    Pop-Location
}
